plugins {
	id 'org.springframework.boot' version '3.5.10'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'net.ironoc.message'
version = '1.0.4-RELEASE'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-messaging'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

test {
	useJUnitPlatform()
}
